=== ailabstw/FLaVor/flavor/schema/aicoco.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/AiCOCOFormat",
  "definitions": {
    "AiCOCOFormat": {
      "additionalProperties": false,
      "properties": {
        "images": {
          "items": {
            "$ref": "#/definitions/AiImage"
          },
          "type": "array"
        },
        "annotations": {
          "items": {
            "$ref": "#/definitions/AiAnnotation"
          },
          "type": "array"
        },
        "categories": {
          "items": {
            "$ref": "#/definitions/AiCategory"
          },
          "type": "array"
        },
        "regressions": {
          "items": {
            "$ref": "#/definitions/AiRegression"
          },
          "type": "array"
        },
        "objects": {
          "items": {
            "$ref": "#/definitions/AiObject"
          },
          "type": "array"
        },
        "meta": {
          "$ref": "#/definitions/AiMeta"
        }
      },
      "required": [
        "images",
        "annotations",
        "categories",
        "regressions",
        "objects",
        "meta"
      ],
      "type": "object"
    },
    "AiImage": {
      "properties": {
        "category_ids": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "file_name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "index": {
          "type": "number"
        },
        "regressions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/AiRegressionItem"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["category_ids", "file_name", "id", "index", "regressions"],
      "type": "object"
    },
    "AiAnnotation": {
      "properties": {
        "bbox": {
          "anyOf": [
            {
              "items": {
                "items": {
                  "type": "number"
                },
                "maxItems": 4,
                "minItems": 4,
                "type": "array"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "id": {
          "type": "string"
        },
        "image_id": {
          "type": "string"
        },
        "iscrowd": {
          "enum": [0, 1],
          "type": "number"
        },
        "object_id": {
          "type": "string"
        },
        "segmentation": {
          "anyOf": [
            {
              "items": {
                "items": {
                  "type": "number"
                },
                "type": "array"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "bbox",
        "id",
        "image_id",
        "iscrowd",
        "object_id",
        "segmentation"
      ],
      "type": "object"
    },
    "AiCategory": {
      "properties": {
        "color": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "supercategory_id": {
          "type": ["string", "null"]
        }
      },
      "required": ["id", "name", "supercategory_id"],
      "type": "object"
    },
    "AiRegression": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "superregression_id": {
          "type": ["string", "null"]
        },
        "unit": {
          "type": "string"
        }
      },
      "required": ["id", "superregression_id", "name"],
      "type": "object"
    },
    "AiRegressionItem": {
      "additionalProperties": false,
      "properties": {
        "regression_id": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": ["regression_id", "value"],
      "type": "object"
    },
    "AiObject": {
      "properties": {
        "category_ids": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "confidence": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "regressions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/AiRegressionItem"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["id", "category_ids", "regressions"],
      "type": "object"
    },
    "AiMeta": {
      "properties": {
        "category_ids": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "regressions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/AiRegressionItem"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "task_type": {
          "enum": ["binary", "multilabel", "multiclass"],
          "type": "string"
        }
      },
      "required": ["category_ids", "regressions"],
      "type": "object"
    }
  }
}

=== ailabstw/FLaVor/tests/unit_tests/inference/strategies/data/aicoco_semantic_seg_w_display.json
{
    "images": [
        {
            "file_name": "image1.dcm",
            "id": "img1",
            "index": 0,
            "category_ids": null,
            "regressions": null
        },
        {
            "file_name": "image2.dcm",
            "id": "img2",
            "index": 1,
            "category_ids": null,
            "regressions": null
        }
    ],
    "categories": [
        {
            "id": "c1",
            "name": "tumor1",
            "supercategory_id": "sc1"
        },
        {
            "id": "c2",
            "name": "tumor2",
            "supercategory_id": "sc1",
            "display": false
        },
        {
            "id": "sc1",
            "name": "lesion",
            "supercategory_id": null
        }
    ],
    "regressions": [],
    "meta": {
        "category_ids": null,
        "regressions": null
    },
    "annotations": [
        {
            "id": "olar3fK0H2r351606S8eq",
            "image_id": "img1",
            "iscrowd": 0,
            "object_id": "6GNvPb8fbyudQ_g1eskZI",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0
                ]
            ]
        },
        {
            "id": "UMmrTIzRqNQ6GsIisJ0hH",
            "image_id": "img2",
            "iscrowd": 0,
            "object_id": "6GNvPb8fbyudQ_g1eskZI",
            "bbox": null,
            "segmentation": [
                [
                    1,
                    2,
                    2,
                    2,
                    3,
                    2,
                    2,
                    2
                ]
            ]
        }
    ],
    "objects": [
        {
            "id": "6GNvPb8fbyudQ_g1eskZI",
            "category_ids": [
                "c1"
            ],
            "regressions": null
        }
    ]
}

=== ailabstw/FLaVor/examples/inference/test_data/cls_reg/expected_reg.json
{
  "images": [
    {
      "file_name": "n02123159_tiger_cat.jpeg",
      "id": "0",
      "index": 0,
      "category_ids": null,
      "regressions": [
        {
          "regression_id": "2WAqGzYtEL6GsWNq6_Z5t",
          "value": -0.03316183015704155
        },
        {
          "regression_id": "i2WqFCPYgb1BWaCUo85bb",
          "value": -0.11870795488357544
        }
      ]
    }
  ],
  "annotations": [],
  "categories": [],
  "regressions": [
    {
      "id": "2WAqGzYtEL6GsWNq6_Z5t",
      "name": "reg0",
      "superregression_id": null
    },
    {
      "id": "i2WqFCPYgb1BWaCUo85bb",
      "name": "reg1",
      "superregression_id": null
    }
  ],
  "objects": [],
  "meta": {
    "category_ids": null,
    "regressions": null
  }
}

=== ailabstw/FLaVor/examples/inference/test_data/det/expected.json
{
  "images": [
    {
      "file_name": "5fb00ac1228969a39cee7cd6678ee704.jpg",
      "id": "0",
      "index": 0,
      "category_ids": null,
      "regressions": null
    }
  ],
  "annotations": [
    {
      "id": "pgzjez6ZWoIrlgn71ZZmt",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "pIxMOea1qo-E1EOjO3HVQ",
      "bbox": [
        [
          165,
          168,
          318,
          324
        ]
      ],
      "segmentation": null
    },
    {
      "id": "Y0FqaQEWxXrZUAIRmJZqZ",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "NVY8V7bD8P5hEpIKanr6X",
      "bbox": [
        [
          102,
          66,
          159,
          148
        ]
      ],
      "segmentation": null
    },
    {
      "id": "o9iTfp-nPDDFm1fobrA5y",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "ujPeIxdGcBefB0hoO8Kz_",
      "bbox": [
        [
          136,
          309,
          206,
          395
        ]
      ],
      "segmentation": null
    },
    {
      "id": "KBKn00PkHup8-c3MysRDR",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "Dxi3aG5fJNcyTCUkphG7L",
      "bbox": [
        [
          52,
          285,
          110,
          375
        ]
      ],
      "segmentation": null
    },
    {
      "id": "EQQjaxrZSMJQjCk5d0eRv",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "CJ7DGLlGOYgtfZSc_9PNk",
      "bbox": [
        [
          322,
          112,
          386,
          208
        ]
      ],
      "segmentation": null
    },
    {
      "id": "gSP8rqUQtRzXho5wqZOjJ",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "qRR2lojoUiInsB1Marj3Z",
      "bbox": [
        [
          302,
          351,
          366,
          416
        ]
      ],
      "segmentation": null
    },
    {
      "id": "xEACAQqOatvjVtY9q5ZQb",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "9aVk-b4R2-pvTrqo23Zo7",
      "bbox": [
        [
          247,
          9,
          318,
          105
        ]
      ],
      "segmentation": null
    },
    {
      "id": "lQvmFFEDqqSuRY38ppVKm",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "HZ9sXTQhbyVqGu28z-d04",
      "bbox": [
        [
          347,
          32,
          415,
          126
        ]
      ],
      "segmentation": null
    },
    {
      "id": "5RX5qO53KkA-gu8Cnu6vB",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "RYHGz-sjqqurgutKmemIy",
      "bbox": [
        [
          40,
          199,
          106,
          301
        ]
      ],
      "segmentation": null
    },
    {
      "id": "9ib-lhPw4o9uM7R7Td4Lt",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "kSOEnYZGGpaxLeYooc-V4",
      "bbox": [
        [
          6,
          290,
          60,
          373
        ]
      ],
      "segmentation": null
    },
    {
      "id": "T1l-mQfWjTUXC3-hH9VCt",
      "image_id": "0",
      "iscrowd": 0,
      "object_id": "785fLBHimCoDbfTAGUwdY",
      "bbox": [
        [
          363,
          300,
          416,
          397
        ]
      ],
      "segmentation": null
    }
  ],
  "categories": [
    {
      "id": "2WAqGzYtEL6GsWNq6_Z5t",
      "name": "RBC",
      "supercategory_id": null,
      "display": true
    },
    {
      "id": "i2WqFCPYgb1BWaCUo85bb",
      "name": "WBC",
      "supercategory_id": null,
      "display": true
    },
    {
      "id": "98df1VQtMMLkBzU-8ICrc",
      "name": "Platelets",
      "supercategory_id": null,
      "display": true
    }
  ],
  "regressions": [],
  "objects": [
    {
      "id": "pIxMOea1qo-E1EOjO3HVQ",
      "category_ids": [
        "98df1VQtMMLkBzU-8ICrc"
      ],
      "regressions": null,
      "confidence": 0.888302206993103
    },
    {
      "id": "NVY8V7bD8P5hEpIKanr6X",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.8173214197158813
    },
    {
      "id": "ujPeIxdGcBefB0hoO8Kz_",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.8119138479232788
    },
    {
      "id": "Dxi3aG5fJNcyTCUkphG7L",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.8112707734107971
    },
    {
      "id": "CJ7DGLlGOYgtfZSc_9PNk",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.8106579184532166
    },
    {
      "id": "qRR2lojoUiInsB1Marj3Z",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.8015463948249817
    },
    {
      "id": "9aVk-b4R2-pvTrqo23Zo7",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.7877304553985596
    },
    {
      "id": "HZ9sXTQhbyVqGu28z-d04",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.7805910706520081
    },
    {
      "id": "RYHGz-sjqqurgutKmemIy",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.7647910118103027
    },
    {
      "id": "kSOEnYZGGpaxLeYooc-V4",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.7384291291236877
    },
    {
      "id": "785fLBHimCoDbfTAGUwdY",
      "category_ids": [
        "i2WqFCPYgb1BWaCUo85bb"
      ],
      "regressions": null,
      "confidence": 0.7303116321563721
    }
  ],
  "meta": {
    "category_ids": null,
    "regressions": null
  }
}

=== ailabstw/FLaVor/examples/inference/test_data/hybrid/expected.json
{
  "images": [
    {
      "file_name": "451c164d-7684-44b1-81b2-956247db765b_20160112_102927.jpg",
      "id": "image_001",
      "index": 0,
      "category_ids": [
        "2WAqGzYtEL6GsWNq6_Z5t"
      ],
      "regressions": null,
      "table_ids": [
        "table_001"
      ]
    }
  ],
  "annotations": [],
  "categories": [
    {
      "id": "2WAqGzYtEL6GsWNq6_Z5t",
      "name": "0",
      "supercategory_id": null
    },
    {
      "id": "i2WqFCPYgb1BWaCUo85bb",
      "name": "1",
      "supercategory_id": null
    }
  ],
  "regressions": [],
  "objects": [],
  "meta": {
    "category_ids": null,
    "regressions": null
  }
}

=== ailabstw/FLaVor/tests/unit_tests/inference/strategies/data/aicoco_instance_seg.json
{
    "images": [
        {
            "file_name": "image1.dcm",
            "id": "img1",
            "index": 0,
            "category_ids": null,
            "regressions": null
        },
        {
            "file_name": "image2.dcm",
            "id": "img2",
            "index": 1,
            "category_ids": null,
            "regressions": null
        }
    ],
    "categories": [
        {
            "id": "c1",
            "name": "tumor1",
            "supercategory_id": "sc1"
        },
        {
            "id": "c2",
            "name": "tumor2",
            "supercategory_id": "sc1"
        },
        {
            "id": "sc1",
            "name": "lesion",
            "supercategory_id": null
        }
    ],
    "regressions": [],
    "meta": {
        "category_ids": null,
        "regressions": null
    },
    "annotations": [
        {
            "id": "4G3637ttIfqyg3icYagYh",
            "image_id": "img1",
            "iscrowd": 0,
            "object_id": "sSuum2z8Vy2Y-hKIS2Jrt",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0
                ]
            ]
        },
        {
            "id": "h55S5iOPDvBdkYBWgMTXn",
            "image_id": "img2",
            "iscrowd": 0,
            "object_id": "arPolt2JzsgwLZoPs-Kg6",
            "bbox": null,
            "segmentation": [
                [
                    1,
                    2,
                    2,
                    2,
                    3,
                    2,
                    2,
                    2
                ]
            ]
        },
        {
            "id": "ROfk3MifIFxw-BuBHkWkH",
            "image_id": "img1",
            "iscrowd": 0,
            "object_id": "1_2-MXlG59ejhuGnmgpI0",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    1,
                    0,
                    2,
                    1,
                    2,
                    1,
                    1
                ]
            ]
        },
        {
            "id": "FrZGD9XbB-CGCDrHEk_k3",
            "image_id": "img2",
            "iscrowd": 0,
            "object_id": "XrED-Plja7u_8U6lpaXW1",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    1,
                    0,
                    2,
                    1,
                    2,
                    2,
                    2,
                    2,
                    1,
                    1,
                    1
                ]
            ]
        }
    ],
    "objects": [
        {
            "id": "sSuum2z8Vy2Y-hKIS2Jrt",
            "category_ids": [
                "c1"
            ],
            "regressions": null
        },
        {
            "id": "arPolt2JzsgwLZoPs-Kg6",
            "category_ids": [
                "c1"
            ],
            "regressions": null
        },
        {
            "id": "1_2-MXlG59ejhuGnmgpI0",
            "category_ids": [
                "c2"
            ],
            "regressions": null
        },
        {
            "id": "XrED-Plja7u_8U6lpaXW1",
            "category_ids": [
                "c2"
            ],
            "regressions": null
        }
    ]
}

=== ailabstw/FLaVor/tests/integration_tests/inference/data/det_example.json
{
    "images": [
        {
            "file_name": "BloodImage_00000_jpg.rf.5fb00ac1228969a39cee7cd6678ee704.jpg",
            "id": "0",
            "index": 0,
            "category_ids": null,
            "regressions": null
        }
    ],
    "annotations": [
        {
            "id": "P0mY_O0cGzPqVrIIEc-VP",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "CijMbSwI2mWFyyjcEF88C",
            "bbox": [
                [
                    168,
                    165,
                    324,
                    318
                ]
            ],
            "segmentation": null
        },
        {
            "id": "XJlA6HsPOgFhwWQw2EgO1",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "kxL6-g_HZmlFAXUhBQ5Mv",
            "bbox": [
                [
                    66,
                    102,
                    148,
                    159
                ]
            ],
            "segmentation": null
        },
        {
            "id": "8mKuot4HAjA8z3Ot16ffN",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "syacdYWvrI61o6nsV5Xsg",
            "bbox": [
                [
                    309,
                    136,
                    395,
                    206
                ]
            ],
            "segmentation": null
        },
        {
            "id": "e4bfFxazkeWwXlehcl0Sm",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "h3u2-VUHjxYsnkILogG_g",
            "bbox": [
                [
                    285,
                    52,
                    375,
                    110
                ]
            ],
            "segmentation": null
        },
        {
            "id": "PlgAbQhZ99FkFezS8tAa-",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "TzE9NuUrEa-i3OKlwqG2o",
            "bbox": [
                [
                    112,
                    322,
                    208,
                    386
                ]
            ],
            "segmentation": null
        },
        {
            "id": "nHbxassOVjwdbG1rlg7_j",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "r-L_OK3ixibVYMZvnZuRh",
            "bbox": [
                [
                    351,
                    302,
                    416,
                    366
                ]
            ],
            "segmentation": null
        },
        {
            "id": "ShmS05LcdM8qH4bLj890u",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "qTiOeN7NtjQ6dhYXvZY9S",
            "bbox": [
                [
                    9,
                    247,
                    105,
                    318
                ]
            ],
            "segmentation": null
        },
        {
            "id": "OG6979Rz-AUI76CeIjJSy",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "8TvXxDYTJ6ezI3X-HEmzP",
            "bbox": [
                [
                    32,
                    347,
                    126,
                    415
                ]
            ],
            "segmentation": null
        },
        {
            "id": "Wzn_Tt2RD49-I4dhIYQ_V",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "pJltfHF7Cgd77i8RElm6m",
            "bbox": [
                [
                    199,
                    40,
                    301,
                    106
                ]
            ],
            "segmentation": null
        },
        {
            "id": "aS1nUKPB1p94LKByd8lbn",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "GNDGWgkRLjYNIDhnku_3Y",
            "bbox": [
                [
                    290,
                    6,
                    373,
                    60
                ]
            ],
            "segmentation": null
        },
        {
            "id": "yxYj8aDP-4X2Rco9X1urH",
            "image_id": "0",
            "iscrowd": 0,
            "object_id": "3WJOhDs9sAZyGI2vVEBit",
            "bbox": [
                [
                    300,
                    363,
                    397,
                    416
                ]
            ],
            "segmentation": null
        }
    ],
    "categories": [
        {
            "id": "XCmP40zJHq0pPeL5-oW_V",
            "name": "RBC",
            "supercategory_id": null,
            "display": true
        },
        {
            "id": "i3JccbWXn76yFusTLSYdh",
            "name": "WBC",
            "supercategory_id": null,
            "display": true
        },
        {
            "id": "kkkwZy0Jb6qakLv7ZQvmv",
            "name": "Platelets",
            "supercategory_id": null,
            "display": true
        }
    ],
    "regressions": [],
    "objects": [
        {
            "id": "CijMbSwI2mWFyyjcEF88C",
            "category_ids": [
                "kkkwZy0Jb6qakLv7ZQvmv"
            ],
            "regressions": null,
            "confidence": 0.888302206993103
        },
        {
            "id": "kxL6-g_HZmlFAXUhBQ5Mv",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.8173213005065918
        },
        {
            "id": "syacdYWvrI61o6nsV5Xsg",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.8119137287139893
        },
        {
            "id": "h3u2-VUHjxYsnkILogG_g",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.8112708330154419
        },
        {
            "id": "TzE9NuUrEa-i3OKlwqG2o",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.8106584548950195
        },
        {
            "id": "r-L_OK3ixibVYMZvnZuRh",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.8015460968017578
        },
        {
            "id": "qTiOeN7NtjQ6dhYXvZY9S",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.7877307534217834
        },
        {
            "id": "8TvXxDYTJ6ezI3X-HEmzP",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.7805907726287842
        },
        {
            "id": "pJltfHF7Cgd77i8RElm6m",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.7647914290428162
        },
        {
            "id": "GNDGWgkRLjYNIDhnku_3Y",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.7384290099143982
        },
        {
            "id": "3WJOhDs9sAZyGI2vVEBit",
            "category_ids": [
                "i3JccbWXn76yFusTLSYdh"
            ],
            "regressions": null,
            "confidence": 0.7303114533424377
        }
    ],
    "meta": {
        "category_ids": null,
        "regressions": null
    }
}

=== ailabstw/FLaVor/tests/unit_tests/inference/strategies/data/aicoco_semantic_seg.json
{
    "images": [
        {
            "file_name": "image1.dcm",
            "id": "img1",
            "index": 0,
            "category_ids": null,
            "regressions": null
        },
        {
            "file_name": "image2.dcm",
            "id": "img2",
            "index": 1,
            "category_ids": null,
            "regressions": null
        }
    ],
    "categories": [
        {
            "id": "c1",
            "name": "tumor1",
            "supercategory_id": "sc1"
        },
        {
            "id": "c2",
            "name": "tumor2",
            "supercategory_id": "sc1"
        },
        {
            "id": "sc1",
            "name": "lesion",
            "supercategory_id": null
        }
    ],
    "regressions": [],
    "meta": {
        "category_ids": null,
        "regressions": null
    },
    "annotations": [
        {
            "id": "FdBshdO8xD2LXq7qIQ-Xx",
            "image_id": "img1",
            "iscrowd": 0,
            "object_id": "eTLHQi3fFBfSlKpcjMEda",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0
                ]
            ]
        },
        {
            "id": "7VE0vJ9zqGWizEFHM4cvz",
            "image_id": "img2",
            "iscrowd": 0,
            "object_id": "eTLHQi3fFBfSlKpcjMEda",
            "bbox": null,
            "segmentation": [
                [
                    1,
                    2,
                    2,
                    2,
                    3,
                    2,
                    2,
                    2
                ]
            ]
        },
        {
            "id": "Z63e8Tgh37nkMGTCoykWZ",
            "image_id": "img1",
            "iscrowd": 0,
            "object_id": "x_0nuLIFqW8bHbm4udqIu",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    1,
                    0,
                    2,
                    1,
                    2,
                    1,
                    1
                ]
            ]
        },
        {
            "id": "eqh1FsmataoUl5AxpZKD_",
            "image_id": "img2",
            "iscrowd": 0,
            "object_id": "x_0nuLIFqW8bHbm4udqIu",
            "bbox": null,
            "segmentation": [
                [
                    0,
                    1,
                    0,
                    2,
                    1,
                    2,
                    2,
                    2,
                    2,
                    1,
                    1,
                    1
                ]
            ]
        }
    ],
    "objects": [
        {
            "id": "eTLHQi3fFBfSlKpcjMEda",
            "category_ids": [
                "c1"
            ],
            "regressions": null
        },
        {
            "id": "x_0nuLIFqW8bHbm4udqIu",
            "category_ids": [
                "c2"
            ],
            "regressions": null
        }
    ]
}
