=== ailabstw/FLaVor/flavor/schema/aicoco.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/AiCOCOFormat",
  "definitions": {
    "AiCOCOFormat": {
      "additionalProperties": false,
      "properties": {
        "images": {
          "items": {
            "$ref": "#/definitions/AiImage"
          },
          "type": "array"
        },
        "annotations": {
          "items": {
            "$ref": "#/definitions/AiAnnotation"
          },
          "type": "array"
        },
        "categories": {
          "items": {
            "$ref": "#/definitions/AiCategory"
          },
          "type": "array"
        },
        "regressions": {
          "items": {
            "$ref": "#/definitions/AiRegression"
          },
          "type": "array"
        },
        "objects": {
          "items": {
            "$ref": "#/definitions/AiObject"
          },
          "type": "array"
        },
        "meta": {
          "$ref": "#/definitions/AiMeta"
        }
      },
      "required": [
        "images",
        "annotations",
        "categories",
        "regressions",
        "objects",
        "meta"
      ],
      "type": "object"
    },
    "AiImage": {
      "properties": {
        "category_ids": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "file_name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "index": {
          "type": "number"
        },
        "regressions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/AiRegressionItem"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["category_ids", "file_name", "id", "index", "regressions"],
      "type": "object"
    },
    "AiAnnotation": {
      "properties": {
        "bbox": {
          "anyOf": [
            {
              "items": {
                "items": {
                  "type": "number"
                },
                "maxItems": 4,
                "minItems": 4,
                "type": "array"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "id": {
          "type": "string"
        },
        "image_id": {
          "type": "string"
        },
        "iscrowd": {
          "enum": [0, 1],
          "type": "number"
        },
        "object_id": {
          "type": "string"
        },
        "segmentation": {
          "anyOf": [
            {
              "items": {
                "items": {
                  "type": "number"
                },
                "type": "array"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "bbox",
        "id",
        "image_id",
        "iscrowd",
        "object_id",
        "segmentation"
      ],
      "type": "object"
    },
    "AiCategory": {
      "properties": {
        "color": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "supercategory_id": {
          "type": ["string", "null"]
        }
      },
      "required": ["id", "name", "supercategory_id"],
      "type": "object"
    },
    "AiRegression": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "superregression_id": {
          "type": ["string", "null"]
        },
        "unit": {
          "type": "string"
        }
      },
      "required": ["id", "superregression_id", "name"],
      "type": "object"
    },
    "AiRegressionItem": {
      "additionalProperties": false,
      "properties": {
        "regression_id": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": ["regression_id", "value"],
      "type": "object"
    },
    "AiObject": {
      "properties": {
        "category_ids": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "confidence": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "regressions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/AiRegressionItem"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["id", "category_ids", "regressions"],
      "type": "object"
    },
    "AiMeta": {
      "properties": {
        "category_ids": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "regressions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/AiRegressionItem"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "task_type": {
          "enum": ["binary", "multilabel", "multiclass"],
          "type": "string"
        }
      },
      "required": ["category_ids", "regressions"],
      "type": "object"
    }
  }
}

=== ailabstw/FLaVor/tests/integration_tests/inference/data/reg_example.json
{
    "images": [
        {
            "file_name": "n02123159_tiger_cat.jpeg",
            "id": "0",
            "index": 0,
            "category_ids": null,
            "regressions": [
                {
                    "regression_id": "VLxX9nWLBV51_87pkuPYB",
                    "value": 1.0711177587509155
                },
                {
                    "regression_id": "VhhUjb4Pr1kyxp4XQ1_GP",
                    "value": -0.29182735085487366
                }
            ]
        }
    ],
    "annotations": [],
    "categories": [],
    "regressions": [
        {
            "id": "VLxX9nWLBV51_87pkuPYB",
            "name": "reg0",
            "superregression_id": null
        },
        {
            "id": "VhhUjb4Pr1kyxp4XQ1_GP",
            "name": "reg1",
            "superregression_id": null
        }
    ],
    "objects": [],
    "meta": {
        "category_ids": null,
        "regressions": null
    }
}
